### ISSUE TITLE
A temp modifier for files / tasks

### ISSUE THREAD

**Issue by rhpvorderman** [openwdl/wdl#195]
[Snakemake has a temporary file modifier](http://snakemake.readthedocs.io/en/stable/tutorial/advanced.html?highlight=temporary#step-6-temporary-and-protected-files). It works like this
```snakemake
output:
    temp("/path/to/my/file")
```
When the tasks that need the output files are finished, the temp files are deleted. This is quite useful if the files can be quickly reproduced but take a lot of disk space.
Would it be possible to add a certain modifier to the `File` type that makes it temporary?
For example `File*` or `File&`.

As an alternative. Somewhere in the runtime a `temp: true` could be set that marks all the outputs of a task as temporary. 

I can imagine this is quite hard to implement. Just throwing it out there as there is already one workflow engine that implemented this feature.

**Comment by orodeh** [comment]
I believe this is conceptually easy to do in Snakemake because it is a goal oriented language. In order to regenerate a temporary file that has been deleted, the engine can invoke the necessary rule(s) again. 

I don't think this is easy to achieve in WDL, which is more like a regular program. It is not built to deal with randomly missing files that were produced earlier.

**Comment by cjllanwarne** [comment]
To me this feels like an engine concern rather than a workflow description concern (It deals with “how” rather than “what”) so I’d avoid making this a first-class WDL citizen.

* It would be possible to implement a clear out in the engine which goes something like: “when the workflow completes, delete any files which were produced but are not present in the workflow outputs”

* it would also probably be possible to implement something more fine-grained via specific parameter meta keys.

* Regarding the one engine I know in detail, I’ll say that this has been brought up several times in the history of Cromwell’s development and every time, when pressed, the requester says that call caching was more important to them than deleting intermediates so they probably wouldn’t actually end up using it.

* One thing you *can* do in Cromwell is export your outputs to a destination directory/bucket after the workflow completes. You’re then free to delete any execution artifacts in the execution directory knowing that the valuable outputs are safe.

**Comment by rhpvorderman** [comment]
Thank you for clarifying. It is clear that this should be handled by the execution engine then. Actually I prefer that to making the WDL syntax more complex.
