### ISSUE TITLE
command parts syntax reinvents the wheel

### ISSUE THREAD

**Issue by antonkulaga** [openwdl/wdl#197]
command parts index is very confusing as it does not look like normal functions.
For instance:
```
${true="--yes" false="--no" boolean_value}
```
can be easly represented as
```
${if(boolean_value) then "--yes" else "--no"}
that is way clearer and it already works with latest Cromwell.
Instead of
```
${sep=", " array_value}
```
I would suggest something like
${array_value.mkList(",")}

Why do you create new weird looking syntax structure instead of just adding a function or two?

**Comment by cjllanwarne** [comment]
Hi @antonkulaga - great comment!

I agree that `if x then y else z` looks much nicer (that's why it was added) but the history is actually the reverse - the `${true= false= ...}` style was the original format and the `if then else` was added later to improve readability.

In a vacuum I'd be in favor of removing and replacing the old style but since it's a breaking change I'd only ever want to make it after a lot of publicity that the old style is being dropped and giving people plenty of notice to update.

**Comment by cjllanwarne** [comment]
I do like the `mkList` function idea - if I were you I'd raise that as a separate issue though since "new more readable feature" can probably happen faster and separately to "now deprecate the old feature".

**Comment by patmagee** [comment]
related #115
