### ISSUE TITLE
Output several strings from Task

### ISSUE THREAD

**Issue by santiagorevale** [openwdl/wdl#212]
Hi there,

I'm trying to run a task that splits a string and should return 5 string output variables. However, I can't figure out how to do that. My task is something like this:

```
task parse_run_folder {
  String run_folder

  command {
    python << CODE
      from datetime import datetime

      # 180503_K00123_0987_BHXDZMBBXX
      folder_name = "${run_folder}".split('/')[-1]
      
      # Split folder in its components
      (run_date, run_machine, run_number, run_flowcellid) = folder_name.split('_')

      # Fix date
      run_date = datetime.strptime(run_date, '%y%m%d').strftime('%Y-%m-%d')

      # Split Flowcell ID into Flowcell Position and Flowcell ID
      run_flowcell_position = run_flowcellid[0]
      run_flowcellid = run_flowcellid[1:]

      print('\n'.join([run_date, run_machine, run_number, run_flowcell_position, run_flowcellid]))
    CODE
  }
  output {
    String run_date = 
    String run_machine = 
    String run_number = 
    String run_flowcell_position = 
    String run_flowcellid = 
  }
}
```

I'm aware that I could output a String array by doing

```
Array[String] values = read_lines(stdout())
```

However, I want to be able to reference the outputs as `parse_run_folder.run_date` and not `parse_run_folder.values[0]`.

Any hint on how to do this would be really appreciated.

Best regards,
Santiago

**Comment by cjllanwarne** [comment]
@santiagorevale for general WDL questions, you might find a more responsive crowd in the future over at the WDL forum (currently hosted here: https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team)

That said, for this particular case you should be able to do the indexing directly in the outputs section after you read the values from stdout:
```wdl
  output {
    Array[String] values = read_lines(stdout())
    String run_date = values[0]
    String run_machine = values[1]
    String run_number = values[2]
    String run_flowcell_position = values[3]
    String run_flowcellid = values[4]
  }
```

**Comment by santiagorevale** [comment]
Thanks @cjllanwarne , that's interesting. I didn't know I was able to do stuff in the output section. The only downside of this is that "values" will also be carried out duplicating the output, right? If there's no other way, I'll just take it as is.

Thanks also for pointing me to that forum.

Cheers,
Santiago

**Comment by cjllanwarne** [comment]
@santiagorevale A few other ideas:
---
You could send the different values into different files as part of the command, eg line 1 goes to `"run_date.txt"` and so on - that way you just need to read the entire contents of each file for each output
---
If the values are short, you could output to TSV format and use the `read_tsv` to get a `Map` rather than an array.
---
Or if you can put the values out as JSON, you can also use `read_json` - one advantage of that is that in WDL 1.0 you can import that JSON into a well typed WDL struct to make sure you get all the fields you want as you read in the json

**Comment by patmagee** [comment]
@santiagorevale I believe the forum @cjllanwarne posted serves as both WDL / Cromwell support for the time being. There is also a gitter page at [https://gitter.im/broadinstitute/cromwell](https://gitter.im/broadinstitute/cromwell), However it is likely they will direct you to the support forum.

I am closing this issue since it looks like it was resolved
