### ISSUE TITLE
Prepending to an optional hack

### ISSUE THREAD

**Issue by EvanTheB** [openwdl/wdl#227]
https://github.com/openwdl/wdl/blame/master/versions/1.0/SPEC.md#L2215

Hello. I am trying to do something I feel ought to be a common practice in WDL. I have a 'File?', and I want to reference the File in the 'command'. I want to quote correctly as I want spaces in filenames to work (although it only deals with one issue, proper escaping is needed!). With a 'File' or a 'String' I do this:
```"~{var_name}"```

If there is some prefix/suffix I do this:
```--abc="~{var_name}".tar.gz```

If my 'File' becomes a 'File?' there is a way to add a prefix:
```~{"--abc=" + var_name}```

And presumably I can quote it or add a suffix like this:
```~{'--abc="' + var_name + '"'}```

Except that the last example above evaluates to 
```"```
When the var_name is null. 

It looks like the String + File? expression linked above is not a fully supported expression. Can anyone help with what I am supposed to be doing in this situation? I come to the spec to try to answer 'what can I put inside ~{}, and the answer seems to not be 'any expression'. Something more like, 'a few different specific and separate to the rest of the language tricks' like sep, and this case. Looking in the spec, I see that 'String + File' is not even an allowed expression in the rest of the language, though File + String is.

Here is my suggestion: 
- ~{} substitutions should be correctly escaped, so I don't have to think about that.
- ~{expr} should support any expression

**Comment by EvanTheB** [comment]
Here is an example of a workaround I am trying to use:
https://github.com/EvanTheB/gatk4-germline-snps-indels/commit/2ab58ba40dfeeec98e32576fc7a0ece0446bfd9c

This is just a way to add a suffix however, I do not think that quoting is working at all in this case.

**Comment by geoffjentry** [comment]
Hi @EvanTheB - If you're looking to spark discussion about what it should be I'd recommend at least pointing folks on the mailing list and/or gitter channels to this issue. When you get to a point where you have a specific request, I'd encourage you to open a PR against the spec.

**Comment by EvanTheB** [comment]
Thanks @geoffjentry, if I make a PR, should it be based on the 1.0 spec.md, or on some other file?

**Comment by geoffjentry** [comment]
@EvanTheB The [developmental spec](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md) is the right place for such a thing

**Comment by cjllanwarne** [comment]
I want to note that it's possible that this is a bug in the execution engine rather than a bug in the SPEC...

In my understanding any expression is valid between `~{}`, and in addition we allow `sep`, `true`/`false` and `default` attributes. My dream is to eventually do away with the need for those special case attributes by making the expressions, well, expressive enough to no longer need them.

In keeping with that "no special cases for placeholders", I *think* (although this is my first impression) I would prefer to support this kind of optional manipulation in the general expression syntax - maybe with `with_prefix` and `with_suffix` methods that could work something like:

  - `with_prefix(prefix, String)` => add the prefix to the `String`
  - `with_prefix(prefix, String?)` => add the prefix to the `String` if it exists, otherwise return empty
  - `with_prefix(prefix, Array[String])` => add the prefix to every `String` in the array

**Comment by cjllanwarne** [comment]
Also as a short term workaround, you can *probably* get this to work with `if then else`, eg
```
task foo {
  input {
    File? in_file
  }
  command <<<
    ~{ if defined(in_file) then 'cat "' + in_file + '"' else 'echo "no file"' }
  >>>
}
```

**Comment by EvanTheB** [comment]
Thanks for that @cjllanwarne , I did not know about the 'defined' method. That solves the problem perfectly. Should I take the bug over to cromwell if this is possibly a bug for them? 

On your with_prefix, is this method better than the '+' operator? I would prefer to see the base operators defined wrt T? and Array[T] types before introducing more std library. But that is just me. If you do prefer a method it might be more general to have a str.join().
