### ISSUE TITLE
Add a `filename_of` function that returns the filename of a file if it were to be downloaded

### ISSUE THREAD

**Issue by TMiguelT** [openwdl/wdl#260]
A lot of WDL scripts make the assumption that you can use `File` and `String` type interchangeably. For example, they might `sub()` a `File` to remove a file extension, whereby it will be converted to a `String`, and then maybe pipe a Bash command to the filepath indicated by that `String`.

However, this poses a problem when dealing with cloud URLs. If you `sub()` an `s3://` or `gs://` `File`, it will be coerced to a `String` which will contain the `s3://` or `gs://` segment, and then any downstream Bash or Python scripts will then attempt to open a path starting in `s3://`, and will fail. This means that WDL that deals with the cloud needs to have workarounds like [this one](https://github.com/gatk-workflows/gatk3-data-processing/blob/88fb7e2ba99b251ff917965640a5fe89f02c4dfd/processing-for-variant-discovery-gatk3.wdl#L82), in one of the official Broad workflows:

```wdl
    String sub_strip_path = "gs://.*/"
    String sub_strip_unmapped = unmapped_bam_suffix + "$"

    # Map reads to reference
    call SamToFastqAndBwaMem {
      input:
        input_bam = unmapped_bam,
        bwa_commandline = bwa_commandline,
        output_bam_basename = sub(sub(unmapped_bam, sub_strip_path, ""), sub_strip_unmapped, "") + ".unmerged",
        ref_fasta = ref_fasta,
        ref_fasta_index = ref_fasta_index,
        ref_dict = ref_dict,
        ref_alt = ref_alt,
        ref_bwt = ref_bwt,
        ref_amb = ref_amb,
        ref_ann = ref_ann,
        ref_pac = ref_pac,
        ref_sa = ref_sa,
        disk_size = flowcell_medium_disk,
        docker = gitc_docker
     }
```

But even this hack isn't ideal. Recently Cromwell added support for AWS S3-based infrastructure, and this script fails to deal with `s3://` URLs, and this will continue to be a problem as new cloud platforms are supported.

To solve this, I propose adding a function like `filename_of(File x) → String y`, which takes a file and returns the `String` path to that file *as it would be if downloaded to the local filesystem*. So for an S3 file, this would return something like `/path/to/file.txt` instead of `s3://path/to/file.txt`. The code for making this conversion must already be in WDL engines, since this conversion has to be done whenever any task is run on a cloud executor. However exposing it to WDL users would be invaluable.

Having such a function would allow the above code to be changed to simply:
```wdl
        output_bam_basename = sub(filename_of(unmapped_bam), sub_strip_unmapped, "") + ".unmerged",
```
And then this code would work on any cloud platform for free.

Does this sound reasonable?

**Comment by cjllanwarne** [comment]
I think this is now available as [basename](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#string-basenamestring) - perhaps you could try that out in the original WDL to confirm whether it does what you want?

**Comment by patmagee** [comment]
I think `basename` does what you are asking. 

at the moment there really are two scenarios both of which are solved by basename:

1. A file is passed as a `String`

In this case, there is no equivalent local path. That is entirely up to you where you put it within the task, or if you localize it at all. If you want the basename do `basename(my_string)`, otherwise you could localize it wherever you want with whatever name you want from it.

2. A file is passed as a `File`

The file will be localized according to the implementations localization strategy in the filesystem. All references to things like `s3`, `gs`, `file://` should be gone at this point. The resolved variable within the context of the task should point to the local path  of the file. If you want the filename here just do `basename` as well

IF what you are REALLY asking for is a way to strip the file protocol from the front of the string,then I would just use `sub` for that and define a `regex` which accounts for `s3:// gs:// file://`. Its worth noting, that any other protocol ie `http`, `ftp` etc does not really translate in any way to a specific `filesystem` and its up to each implementation as to how they localize each file.
