### ISSUE TITLE
Declaration scoping: forward references and masking

### ISSUE THREAD

**Issue by mlin** [openwdl/wdl#265]
Hello all, I'd like to open a discussion on two related issues where the language spec needs some clarification. 

1) Forward references: the Mutect2 workflow under gatk-workflows/gatk4-somatic-snvs-indels has a [declaration whose right-hand side expression](https://github.com/gatk-workflows/gatk4-somatic-snvs-indels/blob/0a82bedcedd2a2176ccced7cc2ed700e37a025f5/mutect2.wdl#L90) refers to a variable `artifact_modes` prior to its lexical declaration. I infer that Cromwell permits this, but, I don't find it articulated clearly in the spec.
    * The development spec does have [an interesting example](https://github.com/openwdl/wdl/blame/master/versions/development/SPEC.md#L1598) where a declaration is bound to an output of a subsequent call. I think it is broken though (`my_task.out` should be `t1.out`?)
2) The [Scope section of the development spec](https://github.com/openwdl/wdl/blame/master/versions/development/SPEC.md#L2232) also shows an example of a 'masking' declaration of `x` where some previous, still-visible declaration had bound `x` to something else. This interacts with the first item because, if there were a previous forward-reference to `x`, which one does it refer to and when? Where is `x : Int` and where is it `x : Array[Int]`? etc.

FWIW, in the [WDL corpi crawled by the miniwdl tests](https://github.com/chanzuckerberg/miniwdl/tree/master/test_corpi) so far, the aforementioned Mutect2 workflow is the only observed example of a forward reference, and there are no observed examples of masking declarations.

If I were starting this from scratch, personally I'd just disallow forward references and masking declarations, but reasonable people can disagree I'm sure...

EDITED: to correct link in bullet point under 1

**Comment by DavyCats** [comment]
Indeed the specs are not very clear on this (as far as I could find), but I always interpreted declarations in WDL to be unordered. So when you declare something it is up to the execution engine to compute a graph and determine when a declaration can be resolved. For example if I were to have a workflow like: 

```wdl
call taskA {}
Int blah = taskB.out + taskC.out
call taskB {input: x=taskA.out}
call taskC {input: x=taskA.out}
```
It would be up to the engine to figure out it has to do:
```
        +--> taskB --+
        |            |
taskA --+            +--> blah
        |            |
        +--> taskC --+

**Comment by geoffjentry** [comment]
@DavyCats That's a good point. Calls are **intentionally** unordered. Although even in your example you could put the `Int blah = ???` line lower down. This also raises the question of if one can `call` a `task` in a forward referenced way - and traditionally the answer has been yes, as some people prefer to put the `workflow` portion at the top of the wf.

I've always interpreted declarations as also being unordered and trusting scoping rules (which might themselves be insufficient currently). I could be argued away from that, but would like a good explanation for why they differ from calls

**Comment by cjllanwarne** [comment]
Hi Mike - 

I agree with @geoffjentry and @DavyCats that in my understanding declarations, like calls, are unordered within the WDL, and given an order due to their position as nodes in the calculated DAG. I think this is fine so long as we disallow multiple ambiguous declarations (which leads me to...)

Regarding the scoping example (and I have an existing PR https://github.com/openwdl/wdl/pull/257 to remove another one of these), I believe that this is an example of call blocks being richer in our original imagination than they actually ended up being (back when spec changes weren't gated on actually being implemented...). Specifically, none of the grammar files have ever allowed this construct and therefore I believe that no in-the-wild WDLs or implementations could either.

**Comment by mlin** [comment]
@DavyCats @geoffjentry thanks -- would you however agree it's too much rope to have *both* forward-references *and* multiple declarations with the same name (in overlapping scopes)? I can prepare a PR with these adjustments/clarifications.

BTW my original post included the wrong link for the bullet point under 1, corrected to this where I think `my_task.out` should be `t1.out`: https://github.com/openwdl/wdl/blame/master/versions/development/SPEC.md#L1598

**Comment by geoffjentry** [comment]
@mlin I'd slightly edit the sentiment to be that you can't allow forward references when scoping rules are not explicitly clear. I believe we're saying the same thing in practice but I'm giving myself some wiggle room in case someone were to make a convincing argument that it makes sense to have multiple declarations in overlapping scopes w/ some deterministic resolution strategy.

As both you and @cjllanwarne note in conjunction there's a combination of "the example is wrong because we never wound up allowing that" and "the example is wrong because of a typo" (your `t1` example)

**Comment by DavyCats** [comment]
I agree that allowing multiple declarations with the same name is not a very nice thing. I image that could get quite confusing rather quickly and I don't really see a reason to allow it.

**Comment by geoffjentry** [comment]
@mlin re your comment that it mostly addresses these things, would you be able to edit and/or leave a comment to describe what you see as the current state of the problem? Or even close if mostly turned out to be fully

**Comment by mlin** [comment]
Yes, #257 is shaping up to be a pretty big spec diff so let's focus there and also i now have #271 open :)
