### ISSUE TITLE
conditional assignment of File variable

### ISSUE THREAD

**Issue by SooLee** [openwdl/wdl#267]
The following 1) works to have a conditional global output, but not 2). Can we have the same feature for Files?

### 1)
```
workflow merge {
    Array[File] smallfiles = []
    if(length(smallfiles)>2) {
        call paste {input: files = smallfiles}
    }
    if(length(smallfiles)<=2) {
        call cat {input: files = smallfiles}
    }
    String step = if(length(smallfiles)>2) then 'paste' else 'cat'
    output {
         String step_run = step
    }
}
```

### 2)
```
workflow merge {
    Array[File] smallfiles = []
    if(length(smallfiles)>2) {
        call paste {input: files = smallfiles}
    }
    if(length(smallfiles)<=2) {
        call cat {input: files = smallfiles}
    }
    File merged0 = if(length(smallfiles)>2) then paste.pasted else cat.concatenated
    output {
        File merged = merged0
    }
}
```
```
ERROR: merged0 is declared as a File but the expression evaluates to a File?:
```

**Comment by DavyCats** [comment]
The problem here is that in workflow 2 you are trying to assign variables defined in an if block (this turns them into optionals) to a non-optional workflow output. Whereas in workflow 1 you're defining the Strings directly in the if-then-else clause. Since if-then-else always returns a value it can return non-optionals (unlike an if-block). Since you are using literals that is the case here.

You can drop the if-then-else and use `select_first([paste.pasted, cat.concatenated])` instead. This will return the first defined value out of the given list as a non-optional.
