### ISSUE TITLE
file output from conditional scattered task

### ISSUE THREAD

**Issue by SooLee** [openwdl/wdl#274]
This one worked.
```
File peak_calls = macs2.bfilt_npeak_bb[0]
```

But not this one.
```
File peak_calls = spp.bfilt_rpeak_peak_bb[0]
```

```
'peak_calls': Cannot build expression for 'chip.peak_calls = spp.bfilt_rpeak_peak_bb[0]': Invalid indexing target. You cannot index a value of type 'Array[File]?'
```

Both `macs2` and `spp` generates a file and were scattered upon an array. The scatter for `spp` is conditional. How do I refer to the first output file of `spp`?

**Comment by yfarjoun** [comment]
i tihnk you need to turn it into a Array[File] first, by doing something like
```wdl
Array[File] ssp_certain = spp
spp_certain.bfilt_rpeak_peak_bb[0]
```

**Comment by SooLee** [comment]
`spp` and `macs2` are tasks that are called like this.

```
scatter(...){
   call macs2
}
```
```
if (...){
   scatter(...){
      call spp
   }
}
```
I did try this
```
Array[File] spppeak = spp.bfilt_rpeak_peak_bb
File peak_calls = select_first([spppeak[0],macs2.bfilt_npeak_bb[0]])
```
But got this error.
```
ERROR: spppeak is declared as a Array[File] but the expression evaluates to a Array[File]?:

        Array[File] spppeak = spp.bfilt_rpeak_peak_bb
```

**Comment by yfarjoun** [comment]
How about
```
Array[File] spppeak = select_first[spp.bfilt_rpeak_peak_bb,[]]
File peak_calls = select_first([spppeak[0],macs2.bfilt_npeak_bb[0]])
```

**Comment by SooLee** [comment]
Got this message.
```
'peak_calls': Cannot build expression for 'chip.peak_calls = select_first([spppeak[0], macs2.bfilt_npeak_bb[0]])': select_first failed. It expects an array of optional values but got Array[File].
```

**Comment by geoffjentry** [comment]
This might be entering “Cromwell bug” territory - it’s worth talking to @cjllanwarne

**Comment by patmagee** [comment]
The underlying issue seems to be the fact that a scatter in an `if` block produces an optional array type, NOT an array type with optional values for your use cases. An optional array cannot be subset, according to your errors. This leads to a very valid question which I think is the ultimate hang up in your situation: Should Optionals be resolved prior to operations such as indexing. 

Resolving the optional produces an `Array[File]` type, however, that cannot be used in the `select_first` clause. but not resolving it leaves the file completely unobtainable.

I wonder if a hacky way to solve this could be something like the following:
```wdl
Array[File] spppeak = select_first[spp.bfilt_rpeak_peak_bb,[]]
if (len(sppeak) > 0) {
   possible_file = spppeak[0]
}
File peak_calls = select_first([possible_file,macs2.bfilt_npeak_bb[0]])
```
