### ISSUE TITLE
WDL/Cromwell version clarifications

### ISSUE THREAD

**Issue by pdiakumis** [openwdl/wdl#291]
Hi folks,

Pardon the potentially silly questions, but I can't seem to find a clear answer in the docs, issues or google group. There's a SPEC for WDL draft-1/2/3, dev, and 1.0 at https://github.com/openwdl/wdl/tree/master/versions.

Which one should I.. focus on? Which version will be (reasonably) compatible with the latest Cromwell release (37 at the moment)? How do I specify I want to try out WDL dev? e.g. `version = development`, and should I be running it with Cromwell dev/master? Or should I stick to, say, `version = draft-3` and ignore the dev stuff as a user?
Thanks for all your work and support!

Kind Regards - Peter

**Comment by rhpvorderman** [comment]
Hi Peter,

You should focus on version 1.0 (https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md).
1.0 is well supported by cromwell (I use it daily and I have not yet had issues with the wdl parsing in cromwell 36 and higher.).

Version development is where new stuff is added. This means this version is unstable. Things you rely on may change. Also it may be buggy because this version by its nature has not been around very long and most bugs with the parsers will not have been discovered yet. To get full support for the WDL-dev SPEC you will need to run Cromwell-dev as it continuously implements any changes in the development spec. The stable versions are not released at a pace that they can keep up with the development spec.

Does that answer your question sufficiently?
