### ISSUE TITLE
Python Wdl_parser documentation

### ISSUE THREAD

**Issue by agraubert** [openwdl/wdl#295]
Hello, I'm getting to a point where it would be profoundly helpful to be able to parse WDLs from within python.  I took a look at your [Python parser](https://github.com/openwdl/wdl/tree/master/versions/draft-2/parsers/python), but I can't make heads or tails of the file.

If someone could help me understand how to use this to parse a WDL file into an AST, I would be happy to test the parser when I use it in my own project and help to fix any issues I find

**Comment by geoffjentry** [comment]
We should probably do away with those parsers as in order to use them effectively you need to understand [Hermes](https://github.com/scottfrazer/hermes) and that's not a skill many people have. 

A few paths you might want to explore:

- I believe that @patmagee was talking about potentially changing the grammar file to a BNF format from the Hermes grammar. That wouldn't help out directly but could enable a more standard path for you
- You could look at how [Toil](https://toil.readthedocs.io/en/latest/) implemented WDL as I believe they used this parser
- You might also want to check out [MiniWDL](https://github.com/chanzuckerberg/miniwdl) spearheaded by @mlin which is a python based implementation. In fact, now that I say this miniwdl might just do what you want in the first place.

**Comment by agraubert** [comment]
Thanks for the tip on miniWDL. This looks like exactly what I needed

**Comment by mlin** [comment]
@agraubert I'm available to help with miniwdl, feel free to open issue there etc...there are still a lot of different directions that project could go and we're eager for community input!
