### ISSUE TITLE
Override runtime parameters at runtime

### ISSUE THREAD

**Issue by illusional** [openwdl/wdl#298]
Is there a way to override runtime parameters at runtime, except for explicitly porting them from the inputs?

eg:
```json
{ "myWorkflow.myTask.runtime.disks": "100 GB" }
```

Or if I did explicitly port them, does (/ should) a value of None in the runtime be override by a backend's default.

**Comment by geoffjentry** [comment]
@illusional One of the many, many, many issues I have with `runtime` is that there's no way to officially do this. It's possible to wire in an input there as any valid WDL expression is viable there, but that requires the WDL to be written that way. You can't do it the way you're suggesting.

One of the other many, many, many issues I have with this is that not everyone sees the current situation as bad :)

I'd personally wholeheartedly support suggested changes to the spec which start to overhaul `runtime`

**Comment by illusional** [comment]
Can I suggest `Specifying / overriding runtime attributes from JSON` as a feature to be added to the openwdl spec. Something similar to [Specifying Workflow Inputs in JSON](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#specifying-workflow-inputs-in-json), and would follow the same resolution order as #141 proposes (backed up by https://github.com/broadinstitute/cromwell/issues/2446). 

Maybe something like:
___

## Specifying / overriding runtime attributes from JSON

Workflow runtime attributes may additionally be specified as key/value pairs within the JSON input. The mapping from JSON or YAML values to WDL values is codified codified similar to the [serialization of task inputs section](#).

In JSON, the user may be able to specify task-specific runtime attributes similar to the following:

{
  "wf.t1.runtime.memory": "16 GB",
  "wf.t2.runtime.cpus": 2,
  "wf.t2.runtime.disks": "100 GB",
  "wf.t3.runtime.arbitrary_key": ["arbitrary value"]
}

As the runtime section consists of key/value pairs, it's up to user to ensure they provide the correct coercible type for the backend they are targeting. See the section on [Type Coercion](#) for more details.

### Resolution Order

Similar to how inputs are resolved, these runtime parameters are resolved in the following order:

1. Inputs provided by the inputs JSON
2. The value provided inline on the task, whether that's an expression or literal value.

**Comment by rhpvorderman** [comment]
> One of the other many, many, many issues I have with this is that not everyone sees the current situation as bad :)

@geoffjentry  I think the current situation with runtime makes it a liability in a cluster environment.
@illusional great addition I would support this if it were a pull request to the spec.

**Comment by DavyCats** [comment]
@rhpvorderman Could you elaborate on how the current runtime is a liability?

Just throwing this out there, but if runtime is going to be reworked it might also be good to consider if there are any more attributes (besides `memory` and `docker`) that should be standardized (eg, disk space, duration, etc.). Probably something for a separate PR though.

**Comment by geoffjentry** [comment]
@illusional I like this idea. As with @rhpvorderman if there were a PR against the spec to make this modification I'd support it.

@rhpvorderman I agree but echo @DavyCats in that I'd be curious to hear your specific thoughts (this might not be the right place for that, but 🤷‍♂️ )

@DavyCats I agree, but this is **definitely** not the right place for that :) Also I've learned a few times over that trying to boil the ocean on fixing *runtime* isn't going to work, so doing it piecemeal will get more traction.

**Comment by rhpvorderman** [comment]
@DavyCats @geoffjentry 
Okay going a bit offtopic here, but I do not like the current runtime because:
- Runtime values cannot be overridden but have to be fed via inputs. I think this is bad design of the current implementation. The runtime values can be specific for a certain environment and should be overridden. This especially important in cluster environments (hence the liability). 
- Runtime values cannot scale with the size of inputs. (We might need to implement something like `filesize(File)` or `dirsize(path)` for that to work). BWA and Centrifuge come to mind, where the amount of memory needed is the space taken up by the index. The rest of the stuff does not take much memory at all.

But once these issues addressed I think the runtime section will be one of the knights in shining armor defending computational biologists from mismanagement of recourses.

I am very glad @illusional has addressed the first issue.

**Comment by geoffjentry** [comment]
@rhpvorderman doesn't [this](https://github.com/broadinstitute/cromwell/blob/develop/centaur/src/main/resources/standardTestCases/runtime_attribute_expressions/runtime_attribute_expressions.wdl#L19) do what your'e describing i the second point?

**Comment by patmagee** [comment]
@rhpvorderman it would certainly be helpful for sizing purposes to have some sort of `size_all()` function, that would compute the total size of all the inputs to the task. I thought we had implemented that at some point, but maybe I am wrong. Other then that though, scaling of runtime values really seems to be a non-trivial task that can only be solved with expressions and custom code. Since there is no universal translation of `X` file size means scale task by a factor of `Y`

**Comment by rhpvorderman** [comment]
> @rhpvorderman doesn't [this](https://github.com/broadinstitute/cromwell/blob/develop/centaur/src/main/resources/standardTestCases/runtime_attribute_expressions/runtime_attribute_expressions.wdl#L19) do what your'e describing i the second point?

Yes. Sorry. Did not know this existed. Thanks a lot @geoffjentry !

**Comment by patmagee** [comment]
Implemented by #315
