### ISSUE TITLE
ability to get Directory file as directory + "/filename"

### ISSUE THREAD

**Issue by antonkulaga** [openwdl/wdl#319]
I opened the issue in Cromwell as I could not get a file inside the Directory ( https://github.com/broadinstitute/cromwell/issues/5041 ) , @geoffjentry pointed out that according to the spec it is the way it should work. For me this type of behavior is total nonsence: why do I need Directory type if I cannot get its children as a file? That is why I suggest to fix WDL specs

**Comment by patmagee** [comment]
To me a directory is a static bundle of files that have some arbitrary structure. because of the limitations of alot of different environments which do not have the concept of directories (ie cloud) its often necessary then to represent a directory as something like a `tar` ball. that is copied wholly into a task. I do not think its really possible to easily "inspect" the contents of the directory in any sort of effiecient way to retrieve a child `File` object without first copying that directory to a task. Nor in fact do I think that should be the behaviour. Having the directory as a non subsetable object within the WDL spec to me makes sense, the same way that not being able to randomly access bytes of a file in WDL makes sense. Since WDL is mostly control logic these type of "heavy lifting" operatioon should be done mostly in the the context of a task where you are free to do whatever you would like

@antonkulaga what sort of changes are you requesting. Also just as a reminder, issues do not necessarily translate into changes. If you would like to see a change come to the spec the best way is to create a PR first.

**Comment by rhpvorderman** [comment]
@antonkulage, Wouldn't a 
```WDL
Map[String, File] example_map
```
Fit your purposes better?
Or
```WDL
struct mydir {
     File blah
     File another_blah
}
mydir.blah  #access membership.
```

I prefer data structures that explicitly list which files are in there. Structs and Arrays fill this niche already. So I do not see why the directory type should be altered.

**Comment by DavyCats** [comment]
@patmagee Wouldn't you still have to unpack such a tarball in order for a task to be run? If so, you would know it's contents.

I don't really see why `Directory + String` would be any different from `File + String`, they simply yield a path which either exists or doesn't.

**Comment by patmagee** [comment]
@DavyCats you would unpack it, but my guess is the unpacking is done wihtin the task itself. Ie the executor would have command, something like the followinh:
```
cp $original_path $task_path.tar && tar -x $task_path.tar
```

**Comment by DavyCats** [comment]
It seems to me that the question concerns task outputs.
eg.
```wdl
task blah {
  input {
    Directory dir
  }
  command {
    echo something > ~{dir}/someFile
  }
  output {
    File out = dir + "/someFile"
  }  
}
```
I can understand that accessing a directory member as an input (or any other kind of declaration) may be problematic, but for outputs, if `Directory + String` indeed just yields a path, this would be no different from any other `File` output. For these, their existence will need to be checked anyway.

**Comment by patmagee** [comment]
@DavyCats I am not 100% sure an operation like that would be valid to be honest. Or at least not valid in all instances Directories are considered a `snapshot` and there is no requirement for directories that be writable. Therefore a a directory might  be readonly, similar to how the localization dircetory for things in cromwell is readonly. In which case, the above task would actually fail.

Originally, I think the intention of the directory is to provide a library of files such as to use for things like Annotation a VCF file. The use cases are obviously broader, but it was not really meant to be something that provides a shared mutable workspace. In the cromwell implementation I believe writing to the localization directory will even fail (when using certain backends) since it is readonly @cjllanwarne correct me if I am wrong here, but this is the behaviour I have observed.  

In the specification it states:
> Even types like File and Directory represent logical "snapshots" of the file or directory at the time when the value was created.

Which to me, is meant to capture the readonly nature of a directory. The original issue seems to be an example of using the directory as a workspace as opposed to a readonly filesystem.

**Comment by geoffjentry** [comment]
FWIW my view is a lot like @patmagee 's - IMO a `Directory` is just an immutable object which happens to have files under the hood. I don't see it as something which can (nor **should**) be subsettable, modified, reveal its inner contents, etc - just the same as I can't slice out an arbitrary set of bytes in a `File` object.

As @rhpvorderman points out, there are other data structures one can use if one wants to access things manually.

**Comment by DavyCats** [comment]
I wasn't looking at this as subsetting or modifying the directory object in any way, but rather as simply creating a file which happens to be in the same path as the Directory. I hadn't considered that the localization could be read-only, indeed, in that case, this wouldn't be an option and the spec should probably discourage it (also writing to a `File + String` should be discouraged I guess, if the localization directory can be read-only in its entirety) in order to keep WDL files backend independent.

**Comment by patmagee** [comment]
Closing this as the behaviour is actually what is expected
