### ISSUE TITLE
conditionals in meta block

### ISSUE THREAD

**Issue by ying-w** [openwdl/wdl#351]
In the if statement example, there is a [conditional in runtime block](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#if-then-else)

I was wondering if conditionals should be allowed in the meta block, for example DNAnexus allows you to choose between parallel downloads (default) vs streaming using meta. I would like the capability of doing something like this:

```wdl
  task mytask {
    input {
        Array[File] bams
        Array[File] bais
    }

    parameter_meta {
        if(len(bams) == 1) {
            bams : "stream"
            bais : "stream"
        }
    }
}
```

I think there was some conversation about this earlier in #73

**Comment by DavyCats** [comment]
Shouldn't this be handled by the runtime block? As far as I understand, `parameter_meta` and `meta` are static key-value pairs intended for documentation/descriptions of the inputs/outputs.

**Comment by patmagee** [comment]
@ying-w Agreeing here with @DavyCats the two meta sections are really meant for documenatation purposes only, althought at the moment they can support nested JSON. In the next version of WDL (2.0), there is a new section called `hints` wich supports expressions which is meant to provide the execution engine with a means of defining additional behaviour to help optimize the run. DNAnexus doing it this way in the parameter_block, is slightly out of spec and really meant to fit their internal use cases.  

I for one would prefer to keep this type of expression out of the parameter meta, since it reinforces behaviour that is not supposed to work nor is it in the spec

**Comment by ying-w** [comment]
Thanks for feedback, I'll pass it along to DNAnexus
