### ISSUE TITLE
Community forum

### ISSUE THREAD

**Issue by shimbalama** [openwdl/wdl#352]
Hi - whats the best place to get some help with WDL in a Stack Overflow style?

Thanks

**Comment by tanasa** [comment]
If I may add somehow a similar question -- in order to learn about WDL developments and new implementations, which website shall we follow : 

-- the current website : https://github.com/openwdl

-- the old websites at Broad : https://gatkforums.broadinstitute.org/wdl/categories/wdl

-- any other resource (STack Overflow, etc ..). 

thanks a lot, 

-- bogdan

**Comment by DavyCats** [comment]
@shimbalama I suppose Stack Overflow could be used, though I don't know if anyone has. (I just made a filter for the `wdl` tag, so if anyone makes a question I should be getting notified.) I think up until now the GATK forums have been used for this, but I don't know if that is still possible with their new website and I didn't really use them myself.

@tanasa I think subscribing to the mailing list and watching this repo is the best way to keep up to date with the developments in the WDL community.

**Comment by tanasa** [comment]
sounds great, thank you !

**Comment by vdauwera** [comment]
In general I agree with @DavyCats that subscribing to this repo/ mailing list is the best way to hear about the latest developments.

On the Broad side we've reorganized a bit, so now we provide our WDL documentation as a subsection in the Terra knowledge base here: https://support.terra.bio/hc/en-us/sections/360007274612-WDL-Documentation. These docs are a bit out of date but we have a project to update them in the near future.

For WDL usage questions you're welcome to post questions in the [Terra Community forum](https://support.terra.bio/hc/en-us/community/topics) or reach out to the Terra support team via the helpdesk. They will answer even if you're using WDL outside of Terra, as we remain committed to supporting users of WDL in the wider community. It's the same team that answers GATK support questions as well so you can also post in the new GATK forum if you're already there, it's all connected under the hood. This new mode of organization is just easier for us to manage (fewer different places to monitor and maintain).

**Comment by tanasa** [comment]
Hi Geraldine, happy to hear from you ! and thank you for all the information ;)

**Comment by illusional** [comment]
I’ll throw out a vote for StackOverflow. I’ll subscribe now for notifications, but as a programmer that’s my first bet because it’s predictable. I don’t really like the amount of other forums workflow languages seem to use.

**Comment by illusional** [comment]
Hey @DavyCats i couldn’t find a tag for WDL, was there one created?

**Comment by DavyCats** [comment]
@illusional It doesn't look like anyone has used it yet, so it won't show up in the search bar. You can still subscribe to it by just typing it in during the filter creation.

**Comment by patmagee** [comment]
+1 to stackoverflow, I think thats the natural location for things to get answered as both a bioinformatician and a software developer. Sadly, my pressence on stackoverlow as a question answerer at the moment is also low so I have 0 reputation

**Comment by ying-w** [comment]
I think either stackoverflow (there is no current [wdl tag](https://stackoverflow.com/questions/tagged/wdl)) or [biostars](https://www.biostars.org/t/wdl/) (SO clone for bioinformatics) would be a good place

**Comment by illusional** [comment]
Does anyone in the community have enough reputation to create a tag?

**Comment by rhpvorderman** [comment]
The irony is that if there would be a lot of WDL questions, we could reach the reputation easily on stack overflow. I did some quick research on stack overflow and I have found some problems with it.

+ Hardly any bioinformatics WDL questions are asked there. That will make it hard to reach reputation of 1500 to get a tag there.
+ There is Microsoft's Flow  Workflow Definition Language (WDL) which is going to hurt our findability (and theirs).

>  biostars (SO clone for bioinformatics) would be a good place

It would be much better. Given that there are already questions asked there about WDL and Cromwell. Plus we contribute to an existing bioinformatics community instead of doing our own thing elsewhere.

So -1 to stackoverflow from me. +1 to biostars.

**Comment by patmagee** [comment]
@rhpvorderman thanks for investigating that. We certainly do not want to be confused with Microsoft's wdl. Since there are already questions regarding wdl and wdl engines in biostars I propose we use that as a community forum. 

What does everyone think?

Also @rhpvorderman is it easier to create a tag in biostars or do we still need an exorbitantly high reputation? I would imagine someone in the wdl community has pretty good reputation on biostars

**Comment by DavyCats** [comment]
Looks like the tag already exists on biostars: https://www.biostars.org/t/wdl/

**Comment by DavyCats** [comment]
I just noticed there is also a bioinformatics stack exchange site ([the reputation needed to create a tag there is only 150](https://bioinformatics.stackexchange.com/help/privileges/create-tags)): https://bioinformatics.stackexchange.com/

**Comment by ying-w** [comment]
Here is some of the history between biostars and bioinformatics SO:

- [Biostars started off on stack exchange](https://meta.stackexchange.com/questions/141143/the-website-biostar-stackexchange-com-has-been-disabled)
- Eventually they built their own [stack](https://github.com/ialbert/biostar-central)
- The move is one way due to [licensing around answers](https://www.biostars.org/p/57747/)
- [Bioinformatics SE](https://area51.meta.stackexchange.com/questions/26719/we-already-have-biostars) got made later

**Comment by patmagee** [comment]
@ying-w thanks for those links. I really did not know the genessis of biostars or why it parted ways with stack exchange. @DavyCats IMO that would be the best place for this. After looking through all of the reasons that @ying-w posted, I tend to agree with alot of them. BioStars answer are Hard to read compared to SE answers. 

My Only concern is that the SE Bioinformatics page is still currently in Beta. That being said, theya re almost 1000 days in beta, with a high level of site visits per day. If we want to use this, we would be conciously making our help forum a `beta` page, which MIGHT be okay, as it will actually help the SE page graduate.

beta status: https://area51.stackexchange.com/proposals/109245/bioinformatics
graduation criteria: https://meta.stackexchange.com/questions/76338/what-are-the-success-criteria-for-an-area-51-beta-site
also this: https://stackoverflow.blog/2010/10/21/when-will-my-site-graduate/

**Comment by patmagee** [comment]
discussion seems to have slowed down on this issue, I am wondering if we have come to any sort of conensus on a good place for a help forum

**Comment by illusional** [comment]
I'd support [bioinformatics stack-exchange](https://bioinformatics.stackexchange.com/), but we'd need someone with 150 RP to create a tag.

**Comment by patmagee** [comment]
@illusional I would be supportive of that as well. If there are enough questions we might even be able to get the stack exachagne graduated

**Comment by rhpvorderman** [comment]
+1 for bioinformatics stackexchange.

**Comment by patmagee** [comment]
so i looks like we have a numer of votes for looking into bioinformatics on stackexcahge. Does anyone here have any RP and can create one or more tags?

**Comment by DavyCats** [comment]
I'm currently at 78 reputation, so not enough but perhaps it is possible to request a tag on the [meta site](https://bioinformatics.meta.stackexchange.com/).

**Comment by patmagee** [comment]
@DavyCats We could potentially request a tag, however it appears that the best way to go about doing this is just start askng WDL questons on the forum. Eventually a tag will be created.

**Comment by patmagee** [comment]
It seems like we are broadly in agreement that bioinformatics.stackexchange would be the most appropriate place to setup a community forum. I will update the documentation to point here!

I thnk the best thing would be just direct people to ask questions there regardless of wether they are tagged or not. We will just need to be dlgent in monitoring the forum and answering any and all questions!
