### ISSUE TITLE
Question about “Prepending a String to an Optional Parameter“

### ISSUE THREAD

**Issue by Catherine2017** [openwdl/wdl#356]
Hi,
When I ran SNPsVariantRecalibrator by version 1.0 wdl, the command is as follows:
command {
    ${gatk_path} --java-options "-Xmx3g -Xms3g" \
      VariantRecalibrator \
      -V ${sites_only_variant_filtered_vcf} \
      -O ${recalibration_filename} \
      --tranches-file ${tranches_filename} \
      --trust-all-polymorphic \
      -tranche ${sep=' -tranche ' recalibration_tranche_values} \
      -an ${sep=' -an ' recalibration_annotation_values} \
      -mode SNP \
      ${"--input-model " + model_report + " --output-tranches-for-scatter "} \
      --max-gaussians 6 \
      --resource:hapmap,known=false,training=true,truth=true,prior=15 ${hapmap_resource_vcf} \
      --resource:omni,known=false,training=true,truth=true,prior=12   ${omni_resource_vcf} \
      --resource:1000G,known=false,training=true,truth=false,prior=10 ${one_thousand_genomes_resource_vcf} \
      --resource:dbsnp,known=true,training=false,truth=false,prior=7  ${dbsnp_resource_vcf}
  }
when "model_report" was undefiend, the script just discarded "--input-model " and did not discarded " --output-tranches-for-scatter ". Could you tell why?

**Comment by patmagee** [comment]
Hey @Catherine2017, the issue with your command is actually due to the way that optionals are handled within string interpolations and the order of operations. when yoiu have  an interpolated expression like `${"--input-model " + model_report + " --output-tranches-for-scatter "}`, where the model_report is an optional and not defined, ONLY  expressions on the immediate LHS will be grouped with the optional `model_report` and ommitted. That means that expressions on the RHS see an empty string instead of being ommitted as well.

For example from my understanding, what is happening is:
```wdl
${"--input-model " + model_report + " --output-tranches-for-scatter "}
==> ${ ("--input-model " + model_report) + " --output-tranches-for-scatter "}
==> ${ "" +  "--output-tranches-for-scatter "}
==> --output-tranches-for-scatter
```

believe it or not this is actually the desired behaviour, as the expression is being read from left to right and follows the rules of precedence defined by the grammar and the engine. You can easily fix this however by adding a little bit of logic to your expression:

```wdl
${ if defined(model_report) then "--input-model " + model_report + " --output-tranches-for-scatter" else "" }
```

This statement returns one string if `model_report` is set, and another string if it is not, and you are guaranteed to get the appropriate behaviour
