### ISSUE TITLE
Add a function to get a list of the values from a Map

### ISSUE THREAD

**Issue by vdauwera** [openwdl/wdl#43]
I have a `Map[String,File]` from which I want to extract the values into an `Array[File]`, that would be equivalent to eg the Java expression `List list = map.values`.

**Justification:** I need to provide multiple files to a task and I don't want to have to hardcode separate arguments for each. I can't just use an Array at the workflow inputs level because I need to be able to call on one of the files specifically in other tasks.

**Worked out use case:**
#### JSON

```
{
    "DoStuffWithKnownSitesWf.known_sites_VCFs_map": { "dbsnp": "dbsnp_138.vcf", "mills": "mills_indels.vcf", "other": "other_sites.vcf" }
    "DoStuffWithKnownSitesWf.known_sites_indices_map": { "dbsnp": "dbsnp_138.vcf.idx", "mills": "mills_indels.vcf.idx", "other": "other_sites.vcf.idx" }
}

```
#### WDL

```
task SomeTool {
    Array[File] known_sites_VCFs
    Array[File] known_sites_indices

    command { 
        doSomething -knownSites ${sep=" -knownSites " known_sites_VCFs}
    }
}

task SomeOtherTool {
    File dbSNP_VCF   
    File dbSNP_index

    command { 
        doSomethingElse --dbsnp  ${dbSNP_VCF}
    }
}

workflow DoStuffWithKnownSitesWf  {
    Map[String, File] known_sites_VCFs_map
    Map[String, File] known_sites_indices_map

    call SomeTool {
        input:
            known_sites_VCFs = known_sites_VCFs_map.values,
            known_sites_indices = known_sites_indices_map.values,
    }

    call SomeOtherTool {
        input:
            dbSNP_VCF = known_sites_VCFs_map["dbsnp"],
            dbSNP_index = known_sites_indices_map["dbsnp"],
    }
}
```

The expression `dbSNP_VCF = known_sites_VCFs_map["dbsnp"]` already works perfectly. But there's currently no way to do a straightforward `known_sites_VCFs = known_sites_VCFs_map.values`. This is the feature request. Actual syntax can be different of course.

Bonus points for making the keys available as well, though I don't have an immediate use case in mind.

Draft implementation: https://github.com/openwdl/wdl/tree/43-map-values

**Comment by vdauwera** [comment]
@kcibul Here's my ticket; let me know if you need any other info.

**Comment by vdauwera** [comment]
https://github.com/broadinstitute/dsde-pipelines/pull/141 shows how this would be used in practice in the GOTC single-sample WDL.

**Comment by freeseek** [comment]
I also feel like this is needed. Python has function `items()`, `keys()`, and `values()` for dictionaries. The current development version of WDL has function `as_pairs()` which is the equivalent of `items()` and function `keys()` but no function `values()`. This can be overcome using scatter, but it would be nice to have this capability inside tasks where scatter is not allowed. It limits the usefulness of maps which are otherwise extremely handy to pass information from workflows to tasks. Basically it feels odd that you have function `zip()`, `as_pairs()`, `as_map()`, and `keys()` with the function `values()` left out.
