### ISSUE TITLE
Tag the 1.0 release?

### ISSUE THREAD

**Issue by mr-c** [openwdl/wdl#465]

**Comment by patmagee** [comment]
Releases are not tagged since all versions are in their own subfolder in the [versions]( https://github.com/openwdl/wdl/tree/main/versions) directory. We had discussed do8ng tagged versions from a single branch pointing to a specific commit be determined our approach better suited the needs of the community.

**Comment by mr-c** [comment]
@patmagee Can this be documented in the readme?
