### ISSUE TITLE
For loop for running tasks by Array

### ISSUE THREAD

**Issue by summerghw** [openwdl/wdl#536]
I understan that i can use `scatter` to  parallel running tasks in a array. But how can i runing tasks one by one （or N steps）in a array ？This is useful in limited computing resources or heavy computing task situation.
ohterwise， can I define every scatter's `concurrent-job-limit`。

**Comment by patmagee** [comment]
Wdl does not enforce any sort of strict ordering. In fact we explicitly call out that tasks can generally be run in any order allowed by the dependency tree.

Running scatters sequentially falls into this category. This then becomes a runtime problem. Some engines may have configuration to limit the total tasks run at once if you look at their config

**Comment by DavyCats** [comment]
Doesn't the engine you are using have an option to configure the total number of available CPUs and memory? 

This is probably something better discussed with the developers of the engine you are using, as this is an issue with the engine's implementation details, rather than a language specification issue.

**Comment by summerghw** [comment]
@DavyCats Thanks for reply. I will try to find out how to configure cromwell to fit my needs.
